### ISSUE TITLE
Does fastsparse.py running generate multithreaded code?

### ISSUE THREAD

**Issue by rexxy-sasori** [marsupialtail/sparsednn#1]

**Comment by marsupialtail** [comment]
No it doesn't. Although it can -- you have to change the start and end field in the Input struct, and then use Python level multithreading. I don't think that will be too efficient though.

**Comment by marsupialtail** [comment]
Basically you can parallelize over C_blocks. So you can set C_blocks to 4, and then start 4 threads, and call the first with start = 0, end = 1, the second with start = 1, end = 2, etc. I don't think this will be very fast.
